name: Test and Auto Merge to Production

on:
  pull_request:
    branches:
      - production
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          if [ -d "./tests" ]; then
            python -m unittest discover tests || exit 1
          fi

  automerge:
      runs-on: ubuntu-latest
      needs: build
      if: success()
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Merge pull request
          if: github.event.pull_request.merged == false
          env:
            GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_PAT }}
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git fetch origin ${{ github.event.pull_request.head.ref }}
            git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            git push origin ${{ github.event.pull_request.head.ref }}
