name: Test and Auto Merge to Production

on:
  pull_request:
    branches:
      - production
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          if [ -d "./tests" ]; then
            python -m unittest discover tests || exit 1
          fi
