name: Test and Merge to Production

on:
  pull_request:
    branches:
      - production
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests

  merge-to-production:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Merge pull request
        run: |
          git checkout production
          git merge --no-ff --no-edit "${{ github.event.pull_request.head.sha }}"
          git push origin production
